import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import fs from "fs";
import path from "path";
import dotenv from "dotenv";

dotenv.config();

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");

const copyToPluginPath = {
	name: 'copy-to-plugin-path',
	setup(build) {
		build.onEnd(() => {
			const pluginPath = process.env.OBSIDIAN_PLUGIN_PATH;
			if (!pluginPath) {
				console.log('OBSIDIAN_PLUGIN_PATH not set in .env, skipping copy.');
				return;
			}

			const filesToCopy = ['main.js', 'manifest.json'];

			filesToCopy.forEach(file => {
				const src = path.join(process.cwd(), file);
				const dest = path.join(pluginPath, file);

				try {
					fs.copyFileSync(src, dest);
					console.log(`Copied ${file} to ${dest}`);
				} catch (e) {
					console.error(`Failed to copy ${file}:`, e);
				}
			});
		});
	},
};

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/closebrackets",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/comment",
		"@codemirror/fold",
		"@codemirror/gutter",
		"@codemirror/highlight",
		"@codemirror/history",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/matchbrackets",
		"@codemirror/panel",
		"@codemirror/rangeset",
		"@codemirror/rectangular-selection",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/stream-parser",
		"@codemirror/text",
		"@codemirror/tooltip",
		"@codemirror/view",
		...builtins],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	plugins: [copyToPluginPath],
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
